### PR TITLE
Added serbian cyrylic and latin

### PR DESCRIPTION
**Pull request by gradzio**

### CODE REVIEW

**Comment by patrickschur** [comment]
Before I can merge your changes, could you change the keys of the json files? 
The key for `sr-Cyrl.json` has to be `sr-Cyrl` and not `sr`. The same for the other file.
Otherwise the tests are failing.

Thanks 😄

**Comment by gradzio** [comment]
Hey Patrick, ahh yes that is correct. Thank you 👍

**Comment by patrickschur** [comment]
You changed the composer.json. ;D

**Comment by gradzio** [comment]
yes I am still new this this forking thing. Let me try to roll back this change

**Comment by patrickschur** [comment]
Take your time, don't hurry. :)

**Comment by gradzio** [comment]
Ok so if I get it right, whenever I will want to make a new branch and merge it to master, then you will get automatic pull request here? or how does it work ? :)

**Comment by patrickschur** [comment]
No, right now you want to merge your branch added-serbian-languages into patrickschur:master.
So whenever you change something in added-serbian-languages it will displayed here.

**Comment by patrickschur** [comment]
Now you have it. Thanks for your contribution. 👍

**Pull request merged**
