### PR TITLE
Add Swahili/Kiswahili (sw)

### PR DESCRIPTION
**Pull request by matthewnessworthy**
Dependant on https://github.com/patrickschur/language-detection/pull/31 since there is a false positive match for `to` if the n-gram is 310

### CODE REVIEW

**Comment by patrickschur** [comment]
You didn't change `sw.php`,  it still contains 1362 entries and not 310.

**Comment by matthewnessworthy** [comment]
@patrickschur sorry about that, i reran the tests a couple of times now and it appears to be corrected.

**Comment by patrickschur** [comment]
Why are the files `tr.php` and `az-Latn.php` effected?

image

**Comment by matthewnessworthy** [comment]
I don't know, I just ran the tests

**Comment by matthewnessworthy** [comment]
I've cleaned up the PR so that only sw is affected

**Pull request merged**
