### PR TITLE
Add: Occitan language

### PR DESCRIPTION
**Pull request by Mejans**
Hello,
I hope the PR is well formed.

Best regards

### CODE REVIEW

**Comment by patrickschur** [comment]
Looks good, except for the empty cell in the table. Can you please fix it? Thanks!

**Comment by Mejans** [comment]
> Looks good, except for the empty cell in the table. Can you please fix it? Thanks!

How?

**Comment by patrickschur** [comment]
By adding the language at the end of the table.

**Comment by Mejans** [comment]
> By adding the language at the end of the table. This way you will not have an empty cell in the middle of the table.

Done!

**Comment by patrickschur** [comment]
Thx

**Pull request merged**
